---
- name: Get Kind Binary
  import_tasks: download_kind.yaml
  when: kind_download_cli | bool

- name: Create Kind Cluster
  import_tasks: create_cluster.yaml

- name: Create and set default namespace
  import_tasks: default_namespace.yaml

- name: Deploy metrics server
  import_tasks: metrics_server.yaml
  when: kind_deploy_metrics_server | bool
