namespace: "seldonio"
name: "k8s"
version: "0.4.0"
readme: "README.md"
authors:
    - "Seldon Technologies Ltd. <hello@seldon.io>"
dependencies:
    "kubernetes.core": ">=2.1.1,<3.0.0"
    "community.docker": ">=1.8.0,<2.0.0"
    "community.crypto": ">=1.7.1,<2.0.0"
license:
    - "Apache 2.0"
tags:
    - seldon
    - kubernetes
    - ecosystem
repository: "https://www.github.com/seldonio/ansible-tools"
build_ignore:
    - .resources
