---
- name: "Create a k8s namespaces: {{ argo_workflows_namespace }}"
  kubernetes.core.k8s:
    name: "{{ argo_workflows_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Install Argo Workflows
  kubernetes.core.helm:
    name: argo-workflows
    release_namespace: "{{ argo_workflows_namespace }}"
    chart_repo_url: "https://argoproj.github.io/argo-helm"
    chart_ref: "argo-workflows"
    chart_version: "{{ argo_workflows_chart_version }}"
    values: "{{ argo_workflows_values }}"

- name: Wait for Argo deployments
  shell: "kubectl rollout status -n {{ argo_workflows_namespace }} deploy/{{ item }}"
  with_items:
    - argo-workflows-server
    - argo-workflows-workflow-controller
  when: argo_workflows_wait_for_deployments | bool

- name: Configure Service RBAC
  import_tasks: rbac.yaml
  when: argo_workflows_configure_rbac | bool
