---
gitea_namespace: gitea-system
gitea_version: 4.0.1

gitea_values: {}
gitea_values_files: []

gitea_port: "3000"

gitea_create_virtualservice: true
gitea_virtualservice_gateway: istio-system/seldon-gateway

gitea_wait_for_deployments: true
