---
- name: Deploy Postgres Operator by Zalando
  kubernetes.core.helm:
    name: postgres-operator
    release_namespace: "{{ postgres_operator_namespace }}"
    chart_ref: "{{ seldon_cache_directory }}/postgres-operator/charts/postgres-operator"
    values: "{{ postgres_operator_values }}"
    values_files: "{{ postgres_operator_values_files }}"
