---
knative_eventing_version: "knative-v1.1.0"
knative_eventing_download_url: "https://github.com/knative/eventing/releases/download"

knative_eventing_crds: "{{ knative_eventing_download_url }}/{{ knative_eventing_version }}/eventing-crds.yaml"
knative_eventing_core: "{{ knative_eventing_download_url }}/{{ knative_eventing_version }}/eventing-core.yaml"
knative_eventing_channel: "{{ knative_eventing_download_url }}/{{ knative_eventing_version }}/in-memory-channel.yaml"
knative_eventing_broker: "{{ knative_eventing_download_url }}/{{ knative_eventing_version }}/mt-channel-broker.yaml"

# workaround for: https://github.com/ansible-collections/kubernetes.core/issues/189
# until: https://github.com/yaml/pyyaml/pull/394 is merged
knative_eventing_workaround_issue_189: true

knative_eventing_create_default_broker: false
knative_eventing_default_broker_name: default
knative_eventing_default_broker_namespace: default
