adminUser: admin
adminPassword: admin
sidecar:
  dashboards:
    enabled: true
    label: kafka_dashboard
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: DS_PROMETHEUS
      type: prometheus
      url: "{{ strimzi_kafka_grafana_prometheus_url }}"
      access: proxy
