---
- name: "Get list of deployments in Knative Eventing namespace"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Deployment
    namespace: knative-eventing
  register: knative_eventing_deployments

- name: "Extract names of deployments in knative seriving namespace"
  set_fact:
    knative_eventing_deployment_names: "{{ knative_eventing_deployments.resources | map(attribute='metadata') | map(attribute='name') }}"

- name: "Wait for Knative Eventing deployments"
  shell: "kubectl rollout status -n knative-eventing deploy/{{ item }}"
  with_items: "{{ knative_eventing_deployment_names }}"

- name: "Create a k8s namespace {{ knative_eventing_default_broker_namespace }} "
  kubernetes.core.k8s:
    name: "{{ knative_eventing_default_broker_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Create default broker
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      metadata:
        name: "{{ knative_eventing_default_broker_name }}"
        namespace: "{{ knative_eventing_default_broker_namespace }}"
  when: knative_eventing_create_default_broker | bool
