---
certmanager_version: v1.8.0
certmanager_yaml: "https://github.com/cert-manager/cert-manager/releases/download/{{ certmanager_version }}/cert-manager.yaml"

certmanager_wait_for_deployments: true

certmanager_use_letsencrypt: false
certmanager_certificate_email: ""
certmanager_certificate_domain: ""

certmanager_issuer_yaml: "{{ lookup('template', 'default-seldon-cert-issuer.yaml.j2') | from_yaml }}"
certmanager_certificate_yaml: "{{ lookup('template', 'default-seldon-certificate.yaml.j2') | from_yaml }}"
