---
- name: Install Certmanager
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('url', item, split_lines=False) }}"
  with_items:
    - "{{ certmanager_yaml }}"

- name: Wait for cert-manager pods become ready
  shell: "kubectl rollout status -n cert-manager deploy/{{ item }}"
  with_items:
    - cert-manager
    - cert-manager-cainjector
    - cert-manager-webhook
  when: certmanager_wait_for_deployments | bool
