---
- name: "Install Certmanager"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('url', item, split_lines=False) }}"
  with_items:
    - "{{ certmanager_yaml }}"
  notify: "Wait for rollout - Certmanager"

- name: "Configure Letsencrypt certificates"
  import_tasks: letsencrypt.yaml
  when: certmanager_use_letsencrypt | bool
