---
- name: Create a k8s namespaces
  kubernetes.core.k8s:
    name: "{{ item }}"
    api_version: v1
    kind: Namespace
    state: present
  with_items:
    - "{{ argocd_namespace }}"
    - "{{ gitops_namespaces }}"

- name: Install Argo CD
  kubernetes.core.helm:
    name: argocd
    release_namespace: "{{ argocd_namespace }}"
    chart_repo_url: "https://argoproj.github.io/argo-helm"
    chart_ref: "argo-cd"
    chart_version: "{{ argocd_chart_version }}"
    values: "{{ argocd_values }}"
  notify: "wait for rollout"

- name: Configure ArgoCD VirtualService
  kubernetes.core.k8s:
    state: present
    template: templates/argocd-vs.yaml.j2
  when: argocd_create_virtualservice | bool

- name: Configure ArgoCD Project
  kubernetes.core.k8s:
    state: present
    template: templates/project.j2

- name: Configure ArgoCD Applications
  kubernetes.core.k8s:
    state: present
    template: templates/application.j2
  loop: "{{ gitops_namespaces }}"
  loop_control:
    loop_var: loop_namespace

- name: Configure ArgoCD git repository
  kubernetes.core.k8s:
    state: present
    template: templates/argocd-repository-secret.yaml.j2

- name: Update ArgoCD ConfigMap
  kubernetes.core.k8s:
    state: present
    template: templates/argocd-configmap.yaml.j2

- name: Configure Seldon Deploy git-creds secret
  kubernetes.core.k8s:
    state: present
    template: templates/seldon-deploy-git-creds.yaml.j2

- name: Annotate Gitops Namespaces for Seldon Deploy
  kubernetes.core.k8s:
    name: "{{ item }}"
    api_version: v1
    kind: Namespace
    state: present
    definition:
      metadata:
        annotations:
          git-repo: "{{ gitops_repository }}"
        labels:
          seldon.gitops: "enabled"
  with_items:
    - "{{ gitops_namespaces }}"
