---
- name: Deploy Elasticsearch by OpenDistro
  kubernetes.core.helm:
    name: elasticsearch
    release_namespace: "{{ elastic_opendistro_namespace }}"
    chart_ref: "{{ seldon_cache_directory }}/opendistro-build/helm/opendistro-es"
    values: "{{ elastic_opendistro_values }}"
  notify: "Wait for rollout - OpenDistro Elasticsearch"
