---
- name: Deploy Elasticsearch by OpenDistro
  kubernetes.core.helm:
    name: elasticsearch
    release_namespace: "{{ elastic_opendistro_namespace }}"
    chart_ref: "{{ seldon_cache_directory }}/opendistro-build/helm/opendistro-es"
    values: "{{ elastic_opendistro_values }}"

- name: Wait for Elasticsearch deployments
  kubernetes.core.k8s_info:
    kind: Deployment
    wait: yes
    wait_condition:
      type: Available
      status: "True"
      reason: MinimumReplicasAvailable
    name: "{{ item }}"
    namespace: "{{ elastic_opendistro_namespace }}"
    wait_timeout: 500
  with_items:
    - elasticsearch-opendistro-es-client
    - elasticsearch-opendistro-es-kibana
  when: elastic_opendistro_wait_for_deployments | bool
