---
- name: Deploy Fluentd
  kubernetes.core.helm:
    name: fluentd
    release_namespace: "{{ elastic_opendistro_namespace }}"
    chart_ref: fluentd-elasticsearch
    chart_repo_url: https://kokuwaio.github.io/helm-charts
    chart_version: "{{ fluentd_chart_version }}"
    values: "{{ fluentd_values }}"

- name: Wait for Fluentd DaemonSet
  shell: "kubectl rollout status -n {{ elastic_opendistro_namespace }} daemonset/{{ item }}"
  with_items:
    - fluentd-fluentd-elasticsearch
  when: fluentd_wait_for_deployments | bool
