---
- name: Deploy Elasticsearch by OpenDistro
  kubernetes.core.helm:
    name: elasticsearch
    release_namespace: "{{ elastic_opendistro_namespace }}"
    chart_ref: "{{ seldon_cache_directory }}/opendistro-build/helm/opendistro-es"
    values: "{{ elastic_opendistro_values }}"

- name: Wait for Elasticsearch deployments
  shell: "kubectl rollout status -n {{ elastic_opendistro_namespace }} deploy/{{ item }}"
  with_items:
    - elasticsearch-opendistro-es-client
  when: elastic_opendistro_wait_for_deployments | bool
