---
- name: Install KFServing
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('url', item, split_lines=False) }}"
  with_items:
    - "{{ kfserving_yaml }}"
  notify: "Wait for rollout - KFServing"

- name: Update KfServing ConfigMap
  kubernetes.core.k8s:
    kind: ConfigMap
    name: inferenceservice-config
    namespace: kfserving-system
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: inferenceservice-config
        namespace: kfserving-system
      data:
        ingress: |-
          {
            "ingressGateway" : "istio-system/seldon-gateway",
            "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local",
            "localGateway" : "knative-local-gateway.knative-serving",
            "localGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local"
          }

        logger: |-
          {
            "image" : "kfserving/agent:v0.6.1",
            "memoryRequest": "100Mi",
            "memoryLimit": "1Gi",
            "cpuRequest": "100m",
            "cpuLimit": "1",
            "defaultUrl": "http://broker-ingress.knative-eventing.svc.cluster.local/seldon-logs/default"
          }
