---
- name: Git clone Iter8 repo and checkout {{ iter8_version }}
  ansible.builtin.git:
    version: "{{ iter8_version }}"
    repo: "{{ iter8_repo }}"
    dest: "{{ seldon_cache_directory }}/iter8"
    force: yes
  when: iter8_source_dir is undefined

- name: Set Iter8 Directory
  set_fact:
    iter8_source_dir: "{{ seldon_cache_directory }}/iter8"
  when: iter8_source_dir is undefined

- name: Install Iter8
  ansible.builtin.shell: "kustomize build {{ seldon_cache_directory }}/iter8/install/core | kubectl apply -n {{ iter8_namespace }} -f -"

- name: Wait for Iter8 deployments
  kubernetes.core.k8s_info:
    kind: Deployment
    wait: yes
    wait_condition:
      type: Available
      status: "True"
      reason: MinimumReplicasAvailable
    name: "{{ item }}"
    namespace: "{{ iter8_namespace }}"
    wait_timeout: 360
  with_items:
    - iter8-analytics
    - iter8-controller-manager
  when: iter8_wait_for_deployments | bool
