---
- name: "Install OpenSearch"
  kubernetes.core.helm:
    chart_repo_url: "{{ elastic_opensearch_chart_repo }}"
    chart_ref: "{{ elastic_opensearch_chart_name }}"
    chart_version: "{{ elastic_opensearch_chart_version }}"
    release_namespace: "{{ elastic_opensearch_namespace }}"
    release_name: "opensearch"
    release_state: present
    release_values: "{{ elastic_opensearch_values }}"

- name: "Wait for OpenSearch rollout"
  when: elastic_opensearch_wait_for_deployments | bool
  with_items:
    - "statefulset/opensearch-cluster-master"
  shell: "kubectl rollout status -n {{ elastic_opensearch_namespace }} {{ item }}"
