---
- name: "Create namespaces"
  import_tasks: namespaces.yaml

- name: "Create secrets"
  import_tasks: secrets.yaml

- name: "Install OpenSearch cluster"
  import_tasks: install_opensearch.yaml

- name: "Install Fluentd"
  import_tasks: install_fluentd.yaml
