---
- name: "Ensure {{ elastic_opensearch_secret_name }} secrets exist"
  with_items:
    - "{{ seldon_system_namespace }}"
    - "{{ elastic_opensearch_namespace }}"
  kubernetes.core.k8s:
    namespace: "{{ item }}"
    state: present
    template: templates/elastic_credentials_secret.yaml.j2
