---
- name: Create Namespaces
  import_tasks: namespaces.yaml

- name: Install Kafka Operator
  import_tasks: install.yaml

- name: Create Kafka Cluster
  import_tasks: cluster.yaml
  when: strimzi_kafka_create_cluster | bool

- name: Install metrics
  include_tasks: metrics.yaml
  when: strimzi_kafka_create_metrics | bool
