---
seldon_system_namespace: seldon-system
seldon_monitoring_namespace: "{{ seldon_system_namespace }}"
seldon_monitoring_prometheus_operator_values: "{{ lookup('file', 'prometheus-operator-values.yaml') | from_yaml }}"
seldon_monitoring_prometheus_operator_chart_version: "8.1.12"

seldon_monitoring_create_default_podmonitor: true
seldon_monitoring_podmonitor: "{{ lookup('file', 'podmonitor.yaml') | from_yaml }}"
