---
- name: Configure GitOps
  hosts: localhost
  roles:
    - istio
    - gitea
  vars:

    istio_version: 1.7.6
    istio_verify_install: false

    gitops_user: "seldon"
    gitops_password: "12341234"
    gitops_repo_name: "test-repo"

    external_protocol: "http"
    external_address: ""

    gitea_values:
      gitea:
        admin:
          username: "{{ gitops_user }}"
          password: "{{ gitops_password }}"
          email: "admin@seldon.io"
        config:
          server:
            DOMAIN: "{{ external_address }}"
            ROOT_URL: "{{ external_protocol }}://{{ external_address }}/gitea/"
      service:
        http:
          type: LoadBalancer
