---
- name: Create Kind Cluster
  hosts: localhost
  roles:
    - kind
    - metallb
  vars:
    kind_cluster_name: ansible
    kind_kubectl_default_namespace: seldon

    # For compatible version of image for each kind version please see https://github.com/kubernetes-sigs/kind/releases
    kind_version: v0.14.0
    kind_image_version: kindest/node:v1.21.12@sha256:f316b33dd88f8196379f38feb80545ef3ed44d9197dca1bfd48bcb1583210207
