---
- name: Create Kind Cluster
  hosts: localhost
  roles:
    - kind
    - metallb
  vars:
    kind_cluster_name: ansible
    # For compatible version of image for each kind version please see https://github.com/kubernetes-sigs/kind/releases    
    kind_version: v0.17.0
    kind_image_version: kindest/node:v1.25.3@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1
    kind_config_file: null
    kind_kubectl_default_namespace: seldon
    kind_url:  "https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-darwin-arm64"
