---
- name: Create Kind Cluster
  hosts: localhost
  roles:
    - kind
    - metallb
  vars:
    kind_cluster_name: ansible
    kind_version: v0.11.1
    kind_image_version: kindest/node:v1.21.1@sha256:f4eaad3d61dfe1228b43407dc9db980cd0a2e254588d133762750e605f5f368a
    kind_kubectl_default_namespace: seldon
