---
# Note: seldon_core_analytics is deprecated, use prometheus role instead

- name: "Create a {{ seldon_system_namespace }} namespaces"
  kubernetes.core.k8s:
    name: "{{ seldon_system_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Create Extra Resources
  kubernetes.core.k8s:
    namespace: "{{ seldon_system_namespace }}"
    definition: "{{ item }}"
  with_items: "{{ seldon_core_analytics_extra_resources }}"
  loop_control:
    label: "{{ item.metadata.name }}"

- name: Install Seldon Core Analytics
  kubernetes.core.helm:
    name: seldon-core-analytics
    release_namespace: "{{ seldon_system_namespace }}"
    chart_repo_url: "https://storage.googleapis.com/seldon-charts"
    chart_ref: "seldon-core-analytics"
    chart_version: "{{ seldon_core_analytics_version }}"
    values: "{{ seldon_core_analytics_values }}"
  notify: "Wait for rollout - Seldon Core Analytics"
