---
- name: "Create a {{ seldon_system_namespace }} namespaces"
  kubernetes.core.k8s:
    name: "{{ seldon_system_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Get information about Ingress Gateway
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: istio-ingressgateway
    namespace: istio-system
  register: istio_web_service
  when: seldon_core_analytics_istio_external_ip_required | bool

- name: "Set fact about Instio Ingress Gateway External IP"
  set_fact:
    istio_external_ip: "{{ istio_web_service.resources[0].status.loadBalancer.ingress[0].ip }}"
  when: seldon_core_analytics_istio_external_ip_required | bool

- name: Create Extra Resources
  kubernetes.core.k8s:
    namespace: "{{ seldon_system_namespace }}"
    definition: "{{ item }}"
  with_items: "{{ seldon_core_analytics_extra_resources }}"

- name: Install Seldon Core Analytics
  kubernetes.core.helm:
    name: seldon-core-analytics
    release_namespace: "{{ seldon_system_namespace }}"
    chart_repo_url: "https://storage.googleapis.com/seldon-charts"
    chart_ref: "seldon-core-analytics"
    chart_version: "{{ seldon_core_analytics_version }}"
    values: "{{ seldon_core_analytics_values }}"


- name: Sleep for 5 seconds to give deployments time to appear
  wait_for:
    timeout: 5
  when: seldon_core_analytics_wait_for_deployments | bool

- name: Get list of deployments for Seldon Core Analytics
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Deployment
    namespace: "{{ seldon_system_namespace }}"
    label_selectors:
    - release = seldon-core-analytics
  register: seldon_core_analytics_deployments
  when: seldon_core_analytics_wait_for_deployments | bool

- name: Extract names of deployments for Seldon Core Analytics
  set_fact:
    seldon_core_analytics_deployments_names: "{{ seldon_core_analytics_deployments.resources | map(attribute='metadata') | map(attribute='name') }}"
  when: seldon_core_analytics_wait_for_deployments | bool


- name: Wait for Seldon Core Analytics Deployments
  shell: "kubectl rollout status -n {{ seldon_system_namespace }} deploy/{{ item }}"
  with_items: "{{ seldon_core_analytics_deployments_names }}"
  when: seldon_core_analytics_wait_for_deployments | bool
